table 'Março e Abril - Controle Celular'
	lineageTag: 7e0f7773-90a5-4da1-82b1-225c1ad21aa0

	column 'Cod Loja'
		dataType: string
		lineageTag: bd7d3813-dccc-4c76-8bcb-0dc7b124cfe3
		summarizeBy: none
		sourceColumn: Cod Loja

		annotation SummarizationSetBy = Automatic

	column 'Loja (Venda)'
		dataType: string
		lineageTag: c9f034e1-5914-41c4-84c2-424269a0b4f1
		summarizeBy: none
		sourceColumn: Loja (Venda)

		annotation SummarizationSetBy = Automatic

	column Atend
		dataType: int64
		formatString: 0
		lineageTag: 7e51d4ee-1bbe-405d-9c15-bf38b363b469
		summarizeBy: sum
		sourceColumn: Atend

		annotation SummarizationSetBy = Automatic

	column CPF
		dataType: string
		lineageTag: 1decf22b-64a2-4ff9-b5fa-979993b8fcb9
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4d763da3-f53f-4d85-9d44-d979527f3e49
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 94df3a83-3898-4be7-91db-a7c6e3bd614a
			defaultHierarchy: LocalDateTable_04794417-9e17-4ad3-8a0a-a148f5fb0dec.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Tipo de Ativacao'
		dataType: string
		lineageTag: bea25d41-238a-4c7d-b47b-8a8b9383d8e1
		summarizeBy: none
		sourceColumn: Tipo de Ativacao

		annotation SummarizationSetBy = Automatic

	column 'Plano Servico'
		dataType: string
		lineageTag: bcb15bf3-ec25-47b5-b31d-cc872d1b5599
		summarizeBy: none
		sourceColumn: Plano Servico

		annotation SummarizationSetBy = Automatic

	column NTC
		dataType: int64
		formatString: 0
		lineageTag: 89f61937-1e6c-4d2a-9a9f-3a8ca6054818
		summarizeBy: sum
		sourceColumn: NTC

		annotation SummarizationSetBy = Automatic

	column 'NTC Provisorio'
		dataType: int64
		formatString: 0
		lineageTag: d3b46754-546f-49db-9e89-9712a3ab2550
		summarizeBy: sum
		sourceColumn: NTC Provisorio

		annotation SummarizationSetBy = Automatic

	column Operadora
		dataType: string
		lineageTag: 46f8f1a1-e179-4f19-89e3-68b6ea83210b
		summarizeBy: none
		sourceColumn: Operadora

		annotation SummarizationSetBy = Automatic

	column ICCID
		dataType: double
		lineageTag: 268bad2d-00e9-4346-86eb-c2b968f59774
		summarizeBy: count
		sourceColumn: ICCID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IMEI
		dataType: int64
		formatString: 0
		lineageTag: c1172b9a-03d9-432d-8965-adeacbe98461
		summarizeBy: sum
		sourceColumn: IMEI

		annotation SummarizationSetBy = Automatic

	column 'Descricao do Produto'
		dataType: string
		lineageTag: 27d6dbc7-f8d4-47a1-a36a-7e66496bd6ea
		summarizeBy: none
		sourceColumn: Descricao do Produto

		annotation SummarizationSetBy = Automatic

	column 'Valor Venda'
		dataType: double
		lineageTag: 8199371b-89f4-4262-9afd-aedea0f64852
		summarizeBy: sum
		sourceColumn: Valor Venda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Desconto Total'
		dataType: double
		lineageTag: 7c2fa515-3e71-4663-b987-cbfa686f8671
		summarizeBy: sum
		sourceColumn: Desconto Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Desconto 1'
		dataType: double
		lineageTag: 00956e23-28ad-4371-a6a5-4e7cac63ebb0
		summarizeBy: sum
		sourceColumn: Desconto 1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Motivo
		dataType: string
		lineageTag: 877c3f3f-802d-451c-9cb9-6f83100d2dab
		summarizeBy: none
		sourceColumn: Motivo

		annotation SummarizationSetBy = Automatic

	column Protocolo
		dataType: string
		lineageTag: 9fc6ec30-af7e-437f-9185-7de81daaed2e
		summarizeBy: none
		sourceColumn: Protocolo

		annotation SummarizationSetBy = Automatic

	column 'Desconto 2'
		dataType: int64
		formatString: 0
		lineageTag: d0f947ef-81f0-4c34-acd0-b5332715ebab
		summarizeBy: sum
		sourceColumn: Desconto 2

		annotation SummarizationSetBy = Automatic

	column Motivo_1
		dataType: string
		lineageTag: c83c2d17-11d9-4a6a-baed-efcfebbc121c
		summarizeBy: none
		sourceColumn: Motivo_1

		annotation SummarizationSetBy = Automatic

	column 'Protocolo 2'
		dataType: int64
		formatString: 0
		lineageTag: f53b331f-e524-4fdf-ae6f-596ef61d71b8
		summarizeBy: sum
		sourceColumn: Protocolo 2

		annotation SummarizationSetBy = Automatic

	column 'Desconto 3'
		dataType: int64
		formatString: 0
		lineageTag: 0be7531f-a554-41e7-b5e2-5cb2f4521922
		summarizeBy: sum
		sourceColumn: Desconto 3

		annotation SummarizationSetBy = Automatic

	column 'Motivo 3'
		dataType: string
		lineageTag: e07a9ae7-76ad-4917-be91-14404d893b72
		summarizeBy: none
		sourceColumn: Motivo 3

		annotation SummarizationSetBy = Automatic

	column 'Protocolo 3'
		dataType: string
		lineageTag: 1e7d0df1-e6d5-44c8-87b0-f59b255478b8
		summarizeBy: none
		sourceColumn: Protocolo 3

		annotation SummarizationSetBy = Automatic

	column 'Autorizado Por'
		dataType: string
		lineageTag: fc142e71-4df3-4048-9f05-c2e09431552c
		summarizeBy: none
		sourceColumn: Autorizado Por

		annotation SummarizationSetBy = Automatic

	column 'Valor Tabela'
		dataType: int64
		formatString: 0
		lineageTag: e2d61358-12ae-4b80-8543-9c8e973e1fc7
		summarizeBy: sum
		sourceColumn: Valor Tabela

		annotation SummarizationSetBy = Automatic

	column Tabela
		dataType: string
		lineageTag: 45848e25-711c-4ec0-9349-535253dafbed
		summarizeBy: none
		sourceColumn: Tabela

		annotation SummarizationSetBy = Automatic

	column 'Data Tabela'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 16993ab6-70db-4bff-a64a-4501a89bd50b
		summarizeBy: none
		sourceColumn: Data Tabela

		variation Variation
			isDefault
			relationship: 6548a464-5651-4a53-9941-dc8ec3a2161c
			defaultHierarchy: LocalDateTable_6dd508da-3eee-4d96-b895-2b50f7808c5c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Vendedor
		dataType: string
		lineageTag: 1511707b-2cb1-4aac-8c98-dbf16dbed488
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column 'Numero NF'
		dataType: int64
		formatString: 0
		lineageTag: 6e5dea8d-7e5d-4569-8d6b-85714cb6a5d2
		summarizeBy: sum
		sourceColumn: Numero NF

		annotation SummarizationSetBy = Automatic

	column Mod
		dataType: string
		lineageTag: 0261d775-9087-4d91-8704-66d39cc6c6f3
		summarizeBy: none
		sourceColumn: Mod

		annotation SummarizationSetBy = Automatic

	column 'Area Cabeada'
		dataType: string
		lineageTag: f55cfd7e-ec77-4e27-a130-1fa266d38408
		summarizeBy: none
		sourceColumn: Area Cabeada

		annotation SummarizationSetBy = Automatic

	column Combo
		dataType: string
		lineageTag: e4c3c465-c125-4cbd-8216-7144250980b0
		summarizeBy: none
		sourceColumn: Combo

		annotation SummarizationSetBy = Automatic

	column Contrato
		dataType: int64
		formatString: 0
		lineageTag: 0bf44fa5-0611-4bd3-b297-572add0d8e52
		summarizeBy: sum
		sourceColumn: Contrato

		annotation SummarizationSetBy = Automatic

	column 'Protocolo '
		dataType: int64
		formatString: 0
		lineageTag: 033ad78d-fd7d-48f3-8c27-5c4f75bbd6d1
		summarizeBy: sum
		sourceColumn: "Protocolo "

		annotation SummarizationSetBy = Automatic

	column 'Tipo Cliente'
		dataType: string
		lineageTag: f9bb546d-62ca-4fbc-b80d-b22bb52eb57b
		summarizeBy: none
		sourceColumn: Tipo Cliente

		annotation SummarizationSetBy = Automatic

	column Margem
		dataType: double
		lineageTag: 0f202b8c-962f-4294-a345-5c78f95650ec
		summarizeBy: sum
		sourceColumn: Margem

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %
		dataType: int64
		formatString: 0
		lineageTag: 1c047e0b-274b-45b0-a40e-f53b078d7a43
		summarizeBy: sum
		sourceColumn: %

		annotation SummarizationSetBy = Automatic

	column 'Custo Compra'
		dataType: int64
		formatString: 0
		lineageTag: a76ef609-9e46-4f39-8bf8-3f6eabd32830
		summarizeBy: sum
		sourceColumn: Custo Compra

		annotation SummarizationSetBy = Automatic

	column Rebate
		dataType: double
		lineageTag: bc793c34-958e-45c8-a41a-0d82d2a9809e
		summarizeBy: sum
		sourceColumn: Rebate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adicional Cartao'
		dataType: double
		lineageTag: b5e47c47-e3a0-41c0-94d5-53167f589d7b
		summarizeBy: sum
		sourceColumn: Adicional Cartao

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Valor Cartao'
		dataType: double
		lineageTag: 26365500-e3fe-43bd-968a-5f1998c72043
		summarizeBy: sum
		sourceColumn: Valor Cartao

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Par
		dataType: int64
		formatString: 0
		lineageTag: 42286694-8463-455d-9f37-777c50fcac18
		summarizeBy: sum
		sourceColumn: Par

		annotation SummarizationSetBy = Automatic

	column Comissao
		dataType: double
		lineageTag: 7725a5c8-4986-4f1d-9647-91ccf5a6dc8d
		summarizeBy: sum
		sourceColumn: Comissao

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Comissao Res'
		dataType: decimal
		formatString: "R$"#,0.###############;-"R$"#,0.###############;"R$"#,0.###############
		lineageTag: 0ce3ed4b-a18b-4923-9f18-3127dbf36193
		summarizeBy: sum
		sourceColumn: Comissao Res

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Dt Entrada'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9dc52acf-078a-4aef-a355-f8f47fc47b07
		summarizeBy: none
		sourceColumn: Dt Entrada

		variation Variation
			isDefault
			relationship: 22084b53-bdb3-497d-97b1-a72521092f5c
			defaultHierarchy: LocalDateTable_b3a06010-ad04-4b1e-bf03-aec824f2bc17.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'NF Entrada'
		dataType: int64
		formatString: 0
		lineageTag: a53bcb7d-5648-4cbe-ab4f-93e39389e1dc
		summarizeBy: sum
		sourceColumn: NF Entrada

		annotation SummarizationSetBy = Automatic

	column 'A F'
		dataType: string
		lineageTag: 53d90fd7-7a60-489c-be97-c4361789f286
		summarizeBy: none
		sourceColumn: A F

		annotation SummarizationSetBy = Automatic

	column 'Protocolo GED'
		dataType: int64
		formatString: 0
		lineageTag: 501b28e2-9d89-412a-88d0-1330fc539a35
		summarizeBy: sum
		sourceColumn: Protocolo GED

		annotation SummarizationSetBy = Automatic

	column 'Status GED'
		dataType: string
		lineageTag: 7cba2c2c-aa43-4856-9639-47da10cbb40c
		summarizeBy: none
		sourceColumn: Status GED

		annotation SummarizationSetBy = Automatic

	column 'Situacao Residencial'
		dataType: string
		lineageTag: e0fab8e1-58a1-4d76-a85e-0fb874e49033
		summarizeBy: none
		sourceColumn: Situacao Residencial

		annotation SummarizationSetBy = Automatic

	column 'Dt Instalacao'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8938bc5d-7bed-498f-8ceb-846c6bf15790
		summarizeBy: none
		sourceColumn: Dt Instalacao

		variation Variation
			isDefault
			relationship: f458f89c-508d-4983-ab67-154504583a5a
			defaultHierarchy: LocalDateTable_8d18eba0-5556-4518-b698-794c5d95aebd.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Promocao
		dataType: string
		lineageTag: bd62064f-9e55-4b0a-a660-0cc126dd4876
		summarizeBy: none
		sourceColumn: Promocao

		annotation SummarizationSetBy = Automatic

	column 'Acao de Marketing'
		dataType: string
		lineageTag: b1db2d06-4c62-48d5-a9d1-e604435460fb
		summarizeBy: none
		sourceColumn: Acao de Marketing

		annotation SummarizationSetBy = Automatic

	column Assinatura
		dataType: double
		lineageTag: c7510c13-bba5-456e-8025-d110ed8cafc0
		summarizeBy: sum
		sourceColumn: Assinatura

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Plano Anterior'
		dataType: string
		lineageTag: 9231e2ab-35c6-417c-b331-2dd45739d6c0
		summarizeBy: none
		sourceColumn: Plano Anterior

		annotation SummarizationSetBy = Automatic

	column 'A/F Ant'
		dataType: string
		lineageTag: 0949ee6e-66cb-4f38-b3e0-a1987175672b
		summarizeBy: none
		sourceColumn: A/F Ant

		annotation SummarizationSetBy = Automatic

	column 'Assinatura Ant'
		dataType: double
		lineageTag: c6927494-1b2e-454f-bb70-d98e13834542
		summarizeBy: sum
		sourceColumn: Assinatura Ant

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Delta
		dataType: double
		lineageTag: bcacea81-4d9c-42c0-98fd-415d8b9e7d6d
		summarizeBy: sum
		sourceColumn: Delta

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Aceite por Voz'
		dataType: string
		lineageTag: 8b8debea-d0d3-4faf-8ffd-0b8cfa395ac0
		summarizeBy: none
		sourceColumn: Aceite por Voz

		annotation SummarizationSetBy = Automatic

	column 'Valor Pre'
		dataType: int64
		formatString: 0
		lineageTag: 804325c5-d1af-4b83-9cde-af4ce6066d97
		summarizeBy: sum
		sourceColumn: Valor Pre

		annotation SummarizationSetBy = Automatic

	column Acrescimo
		dataType: double
		lineageTag: 0362f84f-23ff-43c7-a572-f68b0d1afc30
		summarizeBy: sum
		sourceColumn: Acrescimo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Plano do Titular'
		dataType: string
		lineageTag: c2cb6669-45c9-4865-aec7-b6cdcba2ce12
		summarizeBy: none
		sourceColumn: Plano do Titular

		annotation SummarizationSetBy = Automatic

	column 'Loja (Compra)'
		dataType: string
		lineageTag: 41f6b8b5-5a84-4984-913b-f3fe66cb576b
		summarizeBy: none
		sourceColumn: Loja (Compra)

		annotation SummarizationSetBy = Automatic

	column '1 Vencimento'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ceaa6eb4-c934-4041-aa2b-0f061f12ef04
		summarizeBy: none
		sourceColumn: 1 Vencimento

		variation Variation
			isDefault
			relationship: afd4521f-04a9-4b75-8789-0d8bb688587c
			defaultHierarchy: LocalDateTable_75ec384e-37c2-4454-ad4b-2d9265c6b066.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'email Cliente'
		dataType: string
		lineageTag: f336c1f8-e3b8-4d97-bdac-4c6cd0acb5ae
		summarizeBy: none
		sourceColumn: email Cliente

		annotation SummarizationSetBy = Automatic

	column 'Canal de Vendas'
		dataType: string
		lineageTag: 07e4466b-62f5-4af1-a0ab-c331e3d9d99a
		summarizeBy: none
		sourceColumn: Canal de Vendas

		annotation SummarizationSetBy = Automatic

	column Oferta
		dataType: string
		lineageTag: f930f2ab-2d38-4da5-98a7-f712fe95f28f
		summarizeBy: none
		sourceColumn: Oferta

		annotation SummarizationSetBy = Automatic

	column 'Status da Auditoria'
		dataType: string
		lineageTag: ba56b006-1972-4752-bcaa-e38986a50378
		summarizeBy: none
		sourceColumn: Status da Auditoria

		annotation SummarizationSetBy = Automatic

	column CC
		dataType: string
		lineageTag: 8ae97474-415f-406f-8b85-cd3636d38d09
		summarizeBy: none
		sourceColumn: CC

		annotation SummarizationSetBy = Automatic

	column CR
		dataType: string
		lineageTag: a85a0db9-9227-4967-ba05-0914950e5c74
		summarizeBy: none
		sourceColumn: CR

		annotation SummarizationSetBy = Automatic

	column 'Franquia Total'
		dataType: double
		lineageTag: e1014d2c-d9a9-449c-8e2b-6e27c4abc256
		summarizeBy: sum
		sourceColumn: Franquia Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Lancamento
		dataType: dateTime
		formatString: General Date
		lineageTag: 1eb46ce7-49f4-4304-97b7-a8cb5479d2e1
		summarizeBy: none
		sourceColumn: Lancamento

		variation Variation
			isDefault
			relationship: f9763008-71cc-44ad-a32f-f5b3cdd0a999
			defaultHierarchy: LocalDateTable_0251fe22-3ff5-4f52-8d55-0122768d07cb.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Sistema da Claro'
		dataType: string
		lineageTag: dda3fe23-5126-4380-b1b5-9b2869682cd2
		summarizeBy: none
		sourceColumn: Sistema da Claro

		annotation SummarizationSetBy = Automatic

	partition 'Março e Abril - Controle Celular' = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\djmar\Downloads\Março e Abril - Controle Celular.csv"),[Delimiter=";", Columns=74, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Cód Loja", type text}, {"Loja (Venda)", type text}, {"Atend", Int64.Type}, {"CPF", type text}, {"Data", type date}, {"Tipo de Ativação", type text}, {"Plano/Serviço", type text}, {"NTC", Int64.Type}, {"NTC Provisório", Int64.Type}, {"Operadora", type text}, {"ICCID", type number}, {"IMEI", Int64.Type}, {"Descrição do Produto", type text}, {"Valor Venda", type number}, {"Desconto Total", type number}, {"Desconto 1", type number}, {"Motivo", type text}, {"Protocolo", type text}, {"Desconto 2", Int64.Type}, {"Motivo_1", type text}, {"Protocolo 2", Int64.Type}, {"Desconto 3", Int64.Type}, {"Motivo 3", type text}, {"Protocolo 3", type text}, {"Autorizado Por", type text}, {"Valor Tabela", Int64.Type}, {"Tabela", type text}, {"Data Tabela", type date}, {"Vendedor", type text}, {"Número NF", Int64.Type}, {"Mod", type text}, {"Area Cabeada", type text}, {"Combo", type text}, {"Contrato", Int64.Type}, {"Protocolo ", Int64.Type}, {"Tipo Cliente", type text}, {"Margem", type number}, {"%", Int64.Type}, {"Custo Compra", Int64.Type}, {"Rebate", type number}, {"Adicional Cartão", type number}, {"Valor Cartão", type number}, {"Par", Int64.Type}, {"Comissão", type number}, {"Comissão Res", Currency.Type}, {"Dt Entrada", type date}, {"NF Entrada", Int64.Type}, {"A/F", type text}, {"Protocolo GED", Int64.Type}, {"Status GED", type text}, {"Situação Residencial", type text}, {"Dt Instalação", type date}, {"Promoção", type text}, {"Ação de Marketing", type text}, {"Assinatura", type number}, {"Plano Anterior", type text}, {"A/F Ant", type text}, {"Assinatura Ant", type number}, {"Delta", type number}, {"Aceite por Voz", type text}, {"Valor Pré", Int64.Type}, {"Acréscimo", type number}, {"Plano do Titular", type text}, {"Loja (Compra)", type text}, {"1º Vencimento", type date}, {"e-mail Cliente", type text}, {"Canal de Vendas", type text}, {"Oferta", type text}, {"Status da Auditoria", type text}, {"CC", type text}, {"CR", type text}, {"Franquia Total", type number}, {"Lançamento", type datetime}, {"Sistema da Claro", type text}}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Tipo Alterado", "CPF", Splitter.SplitTextByEachDelimiter({"."}, QuoteStyle.Csv, false), {"CPF.1", "CPF.2"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Dividir Coluna por Delimitador",{{"CPF.2", "CPF"}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Renomeadas",{"CPF.1"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas", each true),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Linhas Filtradas",{{"Cód Loja", "Cod Loja"}, {"Tipo de Ativação", "Tipo de Ativacao"}, {"Plano/Serviço", "Plano Servico"}, {"NTC Provisório", "NTC Provisorio"}, {"Descrição do Produto", "Descricao do Produto"}, {"Número NF", "Numero NF"}, {"Adicional Cartão", "Adicional Cartao"}, {"Valor Cartão", "Valor Cartao"}, {"Comissão", "Comissao"}, {"Comissão Res", "Comissao Res"}, {"A/F", "A F"}, {"Situação Residencial", "Situacao Residencial"}, {"Dt Instalação", "Dt Instalacao"}, {"Promoção", "Promocao"}, {"Ação de Marketing", "Acao de Marketing"}, {"Valor Pré", "Valor Pre"}, {"Acréscimo", "Acrescimo"}, {"e-mail Cliente", "email Cliente"}, {"1º Vencimento", "1 Vencimento"}, {"Lançamento", "Lancamento"}})
				in
				    #"Colunas Renomeadas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

